In [1]:
import sys
sys.path.append('..')
import pandas as pd
from bcb import PTAX

In [2]:
ptax = PTAX()

In [3]:
ptax.describe()

EntitySets:
  Moedas
FunctionImports:
  CotacaoMoedaPeriodoFechamento
  CotacaoMoedaAberturaOuIntermediario
  CotacaoMoedaDia
  CotacaoMoedaPeriodo
  CotacaoDolarDia
  CotacaoDolarPeriodo

In [5]:
ep = ptax.get_endpoint('Moedas')
ep.query().limit(10).collect()

  simbolo             nomeFormatado tipoMoeda
0     AUD         Dólar australiano         B
1     CAD           Dólar canadense         A
2     CHF              Franco suíço         A
3     DKK        Coroa dinamarquesa         A
4     EUR                      Euro         B
5     GBP           Libra Esterlina         B
6     JPY                      Iene         A
7     NOK          Coroa norueguesa         A
8     SEK               Coroa sueca         A
9     USD  Dólar dos Estados Unidos         A

In [7]:
ptax.describe('CotacaoDolarDia')

Function: CotacaoDolarDia
Parameters: dataCotacao <str>
EntitySet: _CotacaoDolarDia
EntityType: br.gov.bcb.olinda.servico.PTAX.TipoCotacaoDolar
Properties: cotacaoCompra <float>, cotacaoVenda <float>, dataHoraCotacao <str>

In [15]:
ep = ptax.get_endpoint('CotacaoDolarDia')
ep.query().parameters(dataCotacao='9/12/2022').collect()

   cotacaoCompra  cotacaoVenda          dataHoraCotacao
0         5.1177        5.1183  2022-09-12 13:04:46.736

In [13]:
ptax.describe('CotacaoMoedaPeriodo')

Function: CotacaoMoedaPeriodo
Parameters: moeda <str>, dataInicial <str>, dataFinalCotacao <str>
EntitySet: _CotacaoMoedaPeriodo
EntityType: br.gov.bcb.olinda.servico.PTAX.TipoCotacaoMoeda
Properties: paridadeCompra <float>, paridadeVenda <float>, cotacaoCompra <float>, cotacaoVenda <float>, dataHoraCotacao <str>, tipoBoletim <str>

In [17]:
ep = ptax.get_endpoint('CotacaoMoedaPeriodo')
ep.query().parameters(moeda='AUD', dataInicial='1/1/2022', dataFinalCotacao='1/5/2022').collect()

,paridadeCompra,paridadeVenda,cotacaoCompra,cotacaoVenda,dataHoraCotacao,tipoBoletim
0,0.7243,0.7244,4.0477,4.0487,2022-01-03 10:04:22.186,Abertura
1,0.7221,0.7223,4.0612,4.0628,2022-01-03 11:11:42.883,Intermediário
2,0.7197,0.7198,4.0623,4.0633,2022-01-03 12:09:19.76,Intermediário
3,0.7186,0.7188,4.0704,4.0719,2022-01-03 13:11:50.353,Intermediário
4,0.7186,0.7188,4.0459,4.0475,2022-01-03 13:11:50.357,Fechamento
5,0.7188,0.7189,4.0901,4.0911,2022-01-04 10:05:22.015,Abertura
6,0.7208,0.7209,4.1096,4.1106,2022-01-04 11:05:20.148,Intermediário
7,0.7217,0.7219,4.0767,4.0782,2022-01-04 12:10:19.466,Intermediário
8,0.7246,0.7248,4.1066,4.1082,2022-01-04 13:08:59.118,Intermediário
9,0.7246,0.7248,4.1136,4.1151,2022-01-04 13:08:59.123,Fechamento
10,0.7250,0.7251,4.1155,4.1165,2022-01-05 10:06:19.404,Abertura
11,0.7258,0.7259,4.1125,4.1135,2022-01-05 11:06:19.009,Intermediário
12,0.7264,0.7266,4.1011,4.1027,2022-01-05 12:03:19.428,Intermediário
13,0.7270,0.7271,4.1149,4.1159,2022-01-05 13:07:53.088,Intermediário
14,0.7270,0.7271,4.1164,4.1174,2022-01-05 13:07:53.094,Fechamento

In [23]:
ptax.describe('CotacaoMoedaDia')

Function: CotacaoMoedaDia
Parameters: moeda <str>, dataCotacao <str>
EntitySet: _CotacaoMoedaDia
EntityType: br.gov.bcb.olinda.servico.PTAX.TipoCotacaoMoeda
Properties: paridadeCompra <float>, paridadeVenda <float>, cotacaoCompra <float>, cotacaoVenda <float>, dataHoraCotacao <str>, tipoBoletim <str>

In [24]:
ep = ptax.get_endpoint('CotacaoMoedaDia')
ep.query().parameters(moeda='AUD', dataCotacao='1/31/2022').collect()

,paridadeCompra,paridadeVenda,cotacaoCompra,cotacaoVenda,dataHoraCotacao,tipoBoletim
0,0.7051,0.7053,3.8001,3.8016,2022-01-31 10:11:20.549,Abertura
1,0.7068,0.7070,3.7911,3.7926,2022-01-31 11:04:17.576,Intermediário
2,0.7066,0.7068,3.7920,3.7935,2022-01-31 12:02:19.723,Intermediário
3,0.7051,0.7052,3.7422,3.7432,2022-01-31 13:07:02.5,Intermediário
4,0.7051,0.7052,3.7771,3.7780,2022-01-31 13:07:02.511,Fechamento PTAX